// Copies the DuckDB WASM runtime out of node_modules into public/duckdb and then
// regenerates the first paint bootstrap. Both steps run before next build.
//
// The copy exists because no public CDN is reachable from the build or the
// deploy target. duckdb-wasm ships its loader pointed at jsdelivr by default;
// selectBundle is handed a manual bundle map instead (src/lib/duckdb-client.ts),
// and that map only resolves if these files sit under the site's base path.

import { cp, mkdir, writeFile, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildBootstrap } from './precompute.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const webRoot = resolve(here, '..');
const distDir = join(webRoot, 'node_modules', '@duckdb', 'duckdb-wasm', 'dist');
const outDir = join(webRoot, 'public', 'duckdb');
const mapDistDir = join(webRoot, 'node_modules', 'maplibre-gl', 'dist');
const mapDir = join(webRoot, 'public', 'maplibre');

// mvp is the fallback for engines without WebAssembly exception handling. coi
// needs cross origin isolation headers, which GitHub Pages does not send, so it
// is deliberately not shipped.
const RUNTIME_FILES = [
  'duckdb-mvp.wasm',
  'duckdb-eh.wasm',
  'duckdb-browser-mvp.worker.js',
  'duckdb-browser-eh.worker.js',
];

// MapLibre resolves its own worker from import.meta.url, which after bundling
// points at a Next chunk directory that has no worker file in it. The worker
// then never answers, the GeoJSON source never finishes loading and the map
// renders its background and nothing else, silently. Copying the module here and
// pointing setWorkerUrl at it (src/components/map-canvas.tsx) is the fix. The
// shared module comes along because the worker is an ES module and imports it
// relatively.
const MAPLIBRE_FILES = ['maplibre-gl-worker.mjs', 'maplibre-gl-shared.mjs'];

// The wrapper worker instruments XMLHttpRequest before handing control to the
// DuckDB worker, so range request byte counts can be attributed to queries.
// It cannot postMessage to the client (that channel belongs to DuckDB's own
// protocol and an unexpected frame would desynchronise it), so it broadcasts.
const WRAPPER = (target) => `// Generated by scripts/prepare-assets.mjs. Do not edit.
//
// DuckDB pulls parquet over synchronous XHR with Range headers from inside the
// worker, where the page cannot see it. Wrapping XMLHttpRequest here is the only
// place the transferred byte count is observable. Results leave over a
// BroadcastChannel because the worker's postMessage port is DuckDB's protocol.
(function () {
  var channel = null;
  try {
    channel = new BroadcastChannel('cityflow-net');
  } catch (err) {
    void err;
  }
  var Native = self.XMLHttpRequest;
  function Instrumented() {
    var xhr = new Native();
    var started = 0;
    var url = '';
    var method = '';
    var ranged = false;
    var open = xhr.open;
    xhr.open = function (requestMethod, requestUrl) {
      method = String(requestMethod).toUpperCase();
      url = String(requestUrl);
      started = Date.now();
      return open.apply(xhr, arguments);
    };
    var setHeader = xhr.setRequestHeader;
    xhr.setRequestHeader = function (name, value) {
      if (String(name).toLowerCase() === 'range') ranged = true;
      return setHeader.apply(xhr, arguments);
    };
    xhr.addEventListener('loadend', function () {
      if (!channel) return;
      // A HEAD carries no body no matter what Content-Length claims, and DuckDB
      // opens every file with one. Counting that header as transferred bytes
      // would make a 3 MB file look downloaded when nothing moved but the
      // headers, which is precisely the claim this instrumentation exists to
      // check, so it must not be the thing that gets it wrong.
      var bytes = 0;
      if (method !== 'HEAD') {
        try {
          if (xhr.response && typeof xhr.response.byteLength === 'number') {
            bytes = xhr.response.byteLength;
          } else if (typeof xhr.responseText === 'string') {
            bytes = xhr.responseText.length;
          }
        } catch (err) {
          void err;
        }
      }
      channel.postMessage({
        url: url,
        method: method,
        bytes: bytes,
        ranged: ranged,
        status: xhr.status,
        ms: Date.now() - started,
      });
    });
    return xhr;
  }
  Instrumented.UNSENT = 0;
  Instrumented.OPENED = 1;
  Instrumented.HEADERS_RECEIVED = 2;
  Instrumented.LOADING = 3;
  Instrumented.DONE = 4;
  self.XMLHttpRequest = Instrumented;
})();
importScripts('${target}');
`;

async function main() {
  if (!existsSync(distDir)) {
    throw new Error(`duckdb-wasm dist not found at ${distDir}. Run npm install first.`);
  }
  await rm(outDir, { recursive: true, force: true });
  await mkdir(outDir, { recursive: true });

  for (const file of RUNTIME_FILES) {
    const from = join(distDir, file);
    if (!existsSync(from)) throw new Error(`missing duckdb runtime file: ${from}`);
    await cp(from, join(outDir, file));
  }

  await rm(mapDir, { recursive: true, force: true });
  await mkdir(mapDir, { recursive: true });
  for (const file of MAPLIBRE_FILES) {
    const from = join(mapDistDir, file);
    if (!existsSync(from)) throw new Error(`missing maplibre runtime file: ${from}`);
    await cp(from, join(mapDir, file));
  }
  process.stdout.write(`prepare-assets: copied ${MAPLIBRE_FILES.length} maplibre files into public/maplibre\n`);

  await writeFile(join(outDir, 'cityflow-mvp.worker.js'), WRAPPER('duckdb-browser-mvp.worker.js'), 'utf8');
  await writeFile(join(outDir, 'cityflow-eh.worker.js'), WRAPPER('duckdb-browser-eh.worker.js'), 'utf8');
  process.stdout.write(`prepare-assets: copied ${RUNTIME_FILES.length} duckdb files into public/duckdb\n`);

  await buildBootstrap();
}

main().catch((err) => {
  process.stderr.write(`prepare-assets failed: ${err.stack || err}\n`);
  process.exit(1);
});
